import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Headers from "./headers";
import Script from 'next/script'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shashank's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" >
      <head>
      <meta name="robots" content="all" />
      <meta name="description" content="Hello, I am Shashank and am a Software engineer with 4+ years of experience in Full Stack Developer and currently working at Ellucian." />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossOrigin="anonymous"></link>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossOrigin="anonymous"></Script> */}

         {/* Google tag (gtag.js) */}

{/* <Script src="https://www.googletagmanager.com/gtag/js?id=G-KNSHEPXN7W" strategy="afterInteractive" />

<Script id="google-analytics" strategy="afterInteractive">
  {`
  window.dataLayer = window.dataLayer || []
  function gtag(){
    dataLayer.push(arguments)
  }
  gtag("js", new Date());

  gtag("config", "G-KNSHEPXN7W")
  `}
</Script> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <Headers /> */}
        {children}
      </body>
    </html>
  );
}
